#!/usr/bin/env bash

# Create an RSA key pair with specific requirements
# Name of the private key: school
# Key size: 4096 bits
# Passphrase: betty

# Ensure the file `school` is generated in the current directory
ssh-keygen -b 4096 -t rsa -f ./school -N betty
