#!/usr/bin/env bash

# Install apache2 if it's not installed
sudo apt-get update
sudo apt-get install -y apache2

# Configure apache to respond to localhost
echo "ServerName localhost" | sudo tee /etc/apache2.conf

# Start apache2
sudo service apache2 start
