#!/usr/bin/env bash
# Configure Apache to respond to localhost

echo "ServerName localhost" > /etc/apache2/conf-available/servername.conf
a2enconf servername
echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
