#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server:
declare -i ARGS="$#"
if [ "$ARGS" -lt 4 ];
then
	echo "Usage: 0-transfer_file C:\Users\Inno\Web\index.html 0.0.0.0 karabo-jpg /home/karabo-jpg/.ssh/id_rsa"
	exit 0;
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/";
fi
